### ISSUE TITLE
Incorrect naming of function in ideogram parser module docstring

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio-utils#8]
https://github.com/plotly/dash-bio-utils/blob/b58a2a416bfa51c95328b31ee6c0ab8a7e47f3ce/dash_bio_utils/ideogram_parser.py#L13

This should be "list", not "array".

**Comment by mkcor** [comment]
@shammamah Thanks for reporting! I'm noticing that this module (`ideogram_parser.py`) and the only function it contains (`ncbi_gdp_to_list()`) is *not* used by Dash Bio's (current) [demo apps](https://github.com/plotly/dash-bio/tree/69bcefb1d4cfbecc2a700157488d57eeee4b4460/tests/dashbio_demos).

I was going to revamp this file, noticing a few other inconsistencies, but now I'm thinking we should remove it altogether. Also, I think the bioinformatics community should have a parser for reading datasets from the NCBI Genome Ideogram data bank. Do you agree?

**Comment by shammamah** [comment]
Yes, this looks like a pretty minimal/simple file. We can get rid of it - good catch!
